// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Event_Ideas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Event_Ideas));
        
        string IMigrationMetadata.Id
        {
            get { return "201707220338252_Event_Ideas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
